name: Build Android APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Install EAS CLI
        run: npm install -g eas-cli expo-cli

      - name: Prebuild Native Android Project
        run: npx expo prebuild --platform android --no-install

      - name: Make Gradle Executable
        run: chmod +x android/gradlew

      - name: Assemble Debug APK
        working-directory: android
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IntervalAlarm-APK
          path: android/app/build/outputs/apk/debug/*.apk
        with:
          name: IntervalAlarm-APK
          path: android/app/build/outputs/apk/release/*.apk
